# Generated by Django 5.1.2 on 2024-10-27 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodName', models.CharField(max_length=200, null=True)),
                ('price', models.FloatField(null=True)),
                ('type', models.CharField(max_length=50, null=True)),
                ('cuisine', models.CharField(max_length=50, null=True)),
                ('description', models.TextField(max_length=1000, null=True)),
                ('rating', models.FloatField(null=True)),
                ('image', models.ImageField(blank=True, default='comingsoon.jpg', null=True, upload_to='')),
                ('isDiscounted', models.BooleanField(default=False)),
                ('discountRate', models.IntegerField(blank=True, null=True)),
                ('discountedPrice', models.FloatField(blank=True, null=True)),
                ('dateCreated', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, null=True, unique=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('long', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BannedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bannedOn', models.DateTimeField(auto_now_add=True)),
                ('isBanned', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=200, null=True)),
                ('lastName', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('profilePic', models.ImageField(blank=True, default='default_profile.png', null=True, upload_to='')),
                ('dateCreated', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Canteen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canteenName', models.CharField(max_length=200, null=True)),
                ('canteenPic', models.ImageField(blank=True, default='default_canteen.png', null=True, upload_to='')),
                ('dateCreated', models.DateTimeField(auto_now_add=True, null=True)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='NTUFoodieApp.location')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100, null=True)),
                ('description', models.TextField(max_length=1000, null=True)),
                ('viewed', models.BooleanField(default=False, null=True)),
                ('dateCreated', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(null=True)),
                ('description', models.TextField(max_length=1000, null=True)),
                ('image', models.ImageField(blank=True, default='NTUFOODIElogo.png', null=True, upload_to='')),
                ('dateCreated', models.DateTimeField(auto_now_add=True, null=True)),
                ('food', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='NTUFoodieApp.food')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FlaggedReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(max_length=500, null=True)),
                ('isProcessed', models.BooleanField(default=False)),
                ('dateFlagged', models.DateTimeField(auto_now_add=True)),
                ('flaggedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NTUFoodieApp.review')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storeName', models.CharField(max_length=200, null=True)),
                ('storePic', models.ImageField(blank=True, default='default_store.png', null=True, upload_to='')),
                ('dateCreated', models.DateTimeField(auto_now_add=True, null=True)),
                ('canteen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='NTUFoodieApp.canteen')),
            ],
        ),
        migrations.AddField(
            model_name='food',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='NTUFoodieApp.store'),
        ),
        migrations.CreateModel(
            name='StoreOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=200, null=True)),
                ('lastName', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('profilePic', models.ImageField(blank=True, default='default_profile.png', null=True, upload_to='')),
                ('dateCreated', models.DateTimeField(auto_now_add=True, null=True)),
                ('store', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='NTUFoodieApp.store')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
